### ISSUE TITLE
make transformations callable

### ISSUE THREAD

**Issue by tpapp** [tpapp/TransformVariables.jl#12]
Once https://github.com/JuliaLang/julia/issues/14919 is fixed.

**Comment by tpapp** [comment]
Implemented by #16, but not closing as a reminder to remove workaround once the above issue is fixed.

**Comment by tpapp** [comment]
Julia 1.3 will have this fixed, so when it is released this issue should be revisited.

**Comment by cscherrer** [comment]
Hi @tpapp , I noticed that callable transforms are now deprecated. Can you help me understand why? I think it's very handy to treat transforms as a kind of function. It allows writing other generic methods that take a callable, which could then very easily be a Function or AbstractTransform without a need to write any dispatch code.

I know this issue is very old, but I assume the answer might be very short, and I assume you intend to close this issue anyway (since they're callable now, but won't be for long). So two birds, one stone :)

**Comment by tpapp** [comment]
@cscherrer, thanks for reminding me of this issue. I deprecated the callability cause I don't think it is very good design to arbitrarily pick one direction of the mapping for that (why not the inverse, etc). Generally, if a type `T` supports `f(::T, ...)`, `g(::T, ...)`, `h(::T, ...)`, I no longer think it is good to pick one of these as `(::T)(...)`.

That said, would `transform(t)` returning a callable that transforms its argument solve your API issue?

**Comment by cscherrer** [comment]
I see, so rather than "a function that knows its inverse", an `AbstractTransform` is considered a container that holds a function and its inverse?

If you have `f = transform(t)`, would `inverse(f)` still work?

**Comment by tpapp** [comment]
Yes, that's a good way of phrasing it.

We could make `inverse(f)` work if you need it. So if `t` is a transformation, then
```julia
transform(t, x) == transform(t)(x)
inverse(t, x) == inverse(t)(x) == inverse(transform(t))(x)
```
How does this sound?

**Comment by cscherrer** [comment]
That sounds great, thanks :)

**Comment by tpapp** [comment]
Great. I like to think a bit about API extensions, but if I don't get back to you on this within a week, please feel free to ping me.

**Comment by cscherrer** [comment]
@tpapp Ping! :)

**Comment by tpapp** [comment]
Thanks for the ping, fixing now.
