### ISSUE TITLE
[not an issue] transform for a given distribution

### ISSUE THREAD

**Issue by briochemc** [tpapp/TransformVariables.jl#74]
Given a distribution `d::UnivariateContinuousDistribution` from Distributions.jl, I would like to be able get a suitable change of variables and using TransformVariables seems like it provides exactly the right machinery for that. So I thought maybe I could define something like

```julia
as(Real, d) = as(Real, support(d).lb, support(d).ub)
```

but this does not work because `Inf` and `∞` are not the same. So my questions are
1. How do you guys go about doing that?
2. Is this even a good idea/use of TransformVariables, or should I look for something else?

**Comment by briochemc** [comment]
FYI, my use case and workaround is something like
```julia
using TransformVariables, Distributions, ForwardDiff
to∞(x) = isinf(x) ? TransformVariables.Infinity{x>0}() : x # <- convert `Inf` to `∞`
lb_domain(d::ContinuousUnivariateDistribution) = to∞(minimum(d))
ub_domain(d::ContinuousUnivariateDistribution) = to∞(maximum(d))
import TransformVariables: transform
transform(d::ContinuousUnivariateDistribution) = as(Real, lb_domain(d), ub_domain(d)) # <- transform a distribution directly
f(d::ContinuousUnivariateDistribution) = x -> transform(d)(x)     # make it into a simple function
∇f(d::ContinuousUnivariateDistribution) = x -> ForwardDiff.derivative(f(d), x)     # 1st derivative
∇²f(d::ContinuousUnivariateDistribution) = x -> ForwardDiff.derivative(∇f(d), x)     # 2nd derivative
invf(d::ContinuousUnivariateDistribution) = x -> inverse(transform(d))(x)       # inverse transform
```
Could you comment on this code and on how to improve it if possible?

**Comment by tpapp** [comment]
Sorry for not replying earlier. Generally, some special casing like this is the way to go.

Note that the construct will not be type stable because infinite domains require another kind of transformation anyway. This was the motivation for not supporting `Inf` directly in the API of this package, so that the type instability is not hidden from the user.

**Comment by briochemc** [comment]
No worries! Thanks for replying! Am I correct in that the 
```julia
f(d::ContinuousUnivariateDistribution) = x -> transform(d)(x)     # make it into a simple function
```
line as a function barrier to type instability?

**Comment by briochemc** [comment]
(BTW, it would be great if you could chime in on https://github.com/JuliaStats/Distributions.jl/pull/1217, since you submitted the affine-trasnformation-for-MvNormal PR 🙏 😃)

**Comment by tpapp** [comment]
Yes. Generally I think that the type information (for domain finiteness) could be preserved since it is specific to the distribution, it's just that `maximum` and `minimum` loses it by returning `Inf::Float64`.

I will try to look at that PR, just can't promise anything since I am very busy now. Feel free to ping me in two weeks there if I don't get around to it.
